apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadwmqm4518-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadwmqm4518-tenant-component
    app.kubernetes.io/part-of: loadwmqm4518-tenant-app
  name: loadwmqm4518-tenant-component
  namespace: loadwmqm4518-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadwmqm4518-tenant-component
    weight: null
status: {}
